
version: 2

models:
  - name: session_analysis
    description: "analyses the user web activity trends"
    columns:
      - name: ip
        description: "The IP address of the user."
        tests:
          - unique
          - not_null
      - name: total_session_duration
        description: "The total duration of sessions for the IP address."
      - name: sessions_count
        description: "The total number of sessions for the IP address."
      - name: total_sales
        description: "The total sales amount for the IP address."
      - name: total_returned
        description: "The total returned amount for the IP address."
      - name: most_common_protocol
        description: "The most common network protocol used by the IP address."

  - name: traffic_revenue
    description: "This model computes the total revenue, unique visitors, and total returns for each traffic source in the e-commerce logs data."
    columns:
      - name: traffic_source
        description: "The source of traffic bringing users to the e-commerce website, such as 'organic', 'paid', 'referral', etc."
        tests:
          - not_null
          - unique
      - name: total_revenue
        description: "Total revenue generated from each traffic source."
        tests:
          - not_null
          - relationships:
              to: source('ecommerce_source', 'ecommerce_logs')
              field: sales
      - name: unique_visitors
        description: "Number of unique visitors from each traffic source, identified by distinct IP addresses."
        tests:
          - not_null
      - name: total_returns
        description: "Total amount of returns processed for each traffic source."
        tests:
          - not_null
  
  - name: retention_analysis
    description: "This model evaluates user retention by analyzing the number of active days, total sessions, and the last session date for each user based on their IP address."
    columns:
      - name: ip
        description: "The IP address of the user, representing a unique identifier for sessions."
        tests:
          - not_null
          - unique

      - name: active_days
        description: "The number of distinct days on which the user was active, calculated by counting the unique session start dates."
        tests:
          - not_null
          - accepted_values:
              values: range(0, 365)
              quote: false

      - name: total_sessions
        description: "The total number of sessions initiated by the user."
        tests:
          - not_null
          - accepted_values:
              values: range(0, 10000)
              quote: false

      - name: last_session_date
        description: "The date of the most recent session initiated by the user."
        tests:
          - not_null
          - unique
          - accepted_values:
              values: range("2022-01-01", "2024-12-31")
              quote: true
  
  - name: user_cart_value
    description: "This model calculates the total sales, session count, and average cart value per user based on their IP address."
    columns:
      - name: ip
        description: "The IP address of the user, representing a unique identifier for sessions."
        tests:
          - not_null

      - name: total_sales
        description: "The total sales amount generated by the user."
        tests:
          - not_null
          - relationships:
              to: source('ecommerce_source', 'ecommerce_logs')
              field: sales

      - name: sessions_count
        description: "The total number of sessions initiated by the user."
        tests:
          - not_null
          - accepted_values:
              values: range(0, 10000)
              quote: false

      - name: avg_cart_value
        description: "The average cart value per user, calculated by dividing the total sales by the number of sessions."
        tests:
          - not_null
          - accepted_values:
              values: range(0, 10000)
              quote: false